spring.application.name=restaurant

spring.datasource.url=jdbc:postgresql://ep-late-darkness-a12mxpa0-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_jMRWwIAdvZ64&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_jMRWwIAdvZ64
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true